name: CI
run-name: ${{ github.actor }} - ${{ github.sha }}

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov coverage
          pip install -r requirements.txt

      - name: Lint
        run: |
          cd ../
          flake8 . --show-source --statistics

      - name: Complexity
        run: |
          cd ../
          flake8 . --exit-zero --max-complexity=10 --statistics

      - name: Run tests
        run: |
         python manage.py test
      - name: Generate Report
        run: |
          coverage run --source='.' manage.py test
          coverage report
